-- Crear base de datos
CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE};

-- Crear usuario con permisos completos en esa DB
CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE}.* TO '${MYSQL_USER}'@'%';
FLUSH PRIVILEGES;
